# Generated by Django 5.0.6 on 2024-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
