# Generated by Django 5.0.6 on 2024-06-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_price_range_hotel_price_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='locations',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.region'),
            preserve_default=False,
        ),
    ]
